### ISSUE TITLE
Method of choosing contrib directory doesn't work everywhere

### ISSUE THREAD

**Issue by jwiegley** [Armael/coq-procrastination#7]
The `src/Makefile` appears to determine the installation target by looking for `coqc` and basing the location off that path. However, most Coq packages in the wild respect `COQLIB`.

Mainly, this makes it difficult to package `coq-procrastination` in Nix, because it's trying to install its files into the tree where `coq` itself lives, rather than in the installation path that's specific to `coq-procrastination`.

**Comment by Armael** [comment]
Thank you for the report, and sorry about the hackish makefile! I'm aware about Nix, I just didn't know (up until now) what was the proper way of finding out the install directory.

So, should the makefile use `COQLIB` instead of `$(coqc -where)/user-contrib`? Anyway I'll investigate and fix the Makefile.

**Comment by jwiegley** [comment]
Usually what I do is to not have a `Makefile` at all, but a `_CoqProject` file, and then run:

```
coq_makefile -f _CoqProject -o Makefile
```

Since the generated Makefile will do everything in the right way.

**Comment by Armael** [comment]
That sounds reasonable indeed. I just pushed a commit on master that uses `coq_makefile` to generate the main makefile. Could you tell me if it works for you?

**Comment by Armael** [comment]
Btw I can also do a new release it you need it for easier packaging...

**Comment by jwiegley** [comment]
Not needed on my account, I just pulled directly from GitHub. I'll be trying again after ICFP.

**Comment by jwiegley** [comment]
Seems to work well!

**Comment by Armael** [comment]
Great, thanks!
